# Generated by Django 2.2.12 on 2020-05-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='super',
            new_name='super_id',
        ),
    ]
