# Generated by Django 2.2.12 on 2020-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200512_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='super_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
