# Generated by Django 2.2.7 on 2020-04-26 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_shpd', models.IntegerField()),
                ('faсt_shpd', models.IntegerField()),
                ('plan_rout', models.IntegerField()),
                ('faсt_rout', models.IntegerField()),
                ('plan_pr', models.IntegerField()),
                ('faсt_pr', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
