# Generated by Django 2.2.12 on 2020-05-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='latitude',
            field=models.CharField(max_length=40),
        ),
    ]
