# Generated by Django 2.2.12 on 2020-05-03 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200503_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
