# Generated by Django 2.2.12 on 2020-05-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
