# Generated by Django 2.2.12 on 2020-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_test_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='longitude',
            field=models.FloatField(default=34),
        ),
    ]
