# Generated by Django 2.2.12 on 2020-05-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_test_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
