# Generated by Django 2.2.12 on 2020-05-08 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
